"""Export SFX patches as assembly data tables.

Generates .asm include files matching the 7-byte-per-entry format
used by the C64 game engine (sound_auditor.asm / dankarmada.asm):

    voice(1B), CR(1B), freq_hi(1B), freq_lo(1B), AD(1B), SR(1B), pw_hi(1B)

Separate-table format adds:
    sfx_sweep[]: 6 bytes per entry (target_hi, target_lo, frames, flags, vib_rate, vib_depth)
    sweep_flags: bit 0 = sweep enable, bit 1 = curve (0=linear, 1=exponential), bit 2 = vibrato enable
"""

from __future__ import annotations

from pathlib import Path
from typing import Sequence

from sid_sfx.schema import SfxPatch


# 16-byte exponential curve lookup table (0-255 range, 16 steps).
# Approximates f(x) = 255 * (e^(x/15*3) - 1) / (e^3 - 1) for x in 0..15.
EXP_CURVE_LUT = bytes([
    0, 1, 2, 4, 7, 11, 17, 25,
    36, 51, 72, 101, 140, 178, 218, 255,
])

# Blaster weight table: maps random index (0-7) to blaster variant offset.
# 3/8 xwing, 2/8 heavy_repeater, 1/8 turbolaser, 1/8 tie_cannon, 1/8 ion_cannon
BLASTER_WEIGHTS = bytes([0, 0, 0, 1, 1, 2, 3, 4])


def patch_to_bytes(patch: SfxPatch) -> bytes:
    """Convert a patch to its 7-byte binary representation."""
    return patch.to_bytes()


def patch_to_sweep_bytes(patch: SfxPatch) -> bytes:
    """Convert a patch's sweep + vibrato parameters to 6-byte representation.

    Format: target_hi, target_lo, frames, flags, vib_rate, vib_depth
    flags: bit 0 = sweep enable, bit 1 = curve (0=linear, 1=exp), bit 2 = vibrato enable
    vib_rate: vibrato rate in quarter-Hz units (0-255 → 0-63.75 Hz)
    vib_depth: vibrato depth in SID freq units (high byte only, 0-255)
    """
    flags = 0x00
    target_hi = 0
    target_lo = 0
    frames = 0
    vib_rate = 0
    vib_depth = 0

    if patch.has_sweep:
        flags |= 0x01
        if patch.sweep_type == "exponential":
            flags |= 0x02
        target_hi = patch.sweep_target_hi
        target_lo = patch.sweep_target_lo
        frames = patch.sweep_frames if patch.sweep_frames > 0 else patch.duration_frames

    if patch.has_vibrato:
        flags |= 0x04
        # Encode rate as quarter-Hz (4x), clamp to byte
        vib_rate = min(255, round(patch.vibrato_rate * 4))
        # Encode depth high byte (>> 8), clamp to byte
        vib_depth = min(255, (patch.vibrato_depth >> 8) if patch.vibrato_depth > 255 else patch.vibrato_depth)

    return bytes([
        target_hi,
        target_lo,
        frames & 0xFF,
        flags,
        vib_rate,
        vib_depth,
    ])


def patch_to_asm_line(patch: SfxPatch) -> str:
    """Format a patch as a single .byte directive line."""
    b = patch.to_bytes()
    hex_vals = ", ".join(f"${v:02X}" for v in b)
    return f"    .byte {hex_vals}  ; {patch.name}"


def sweep_to_asm_line(patch: SfxPatch) -> str:
    """Format a patch's sweep/vibrato as a single .byte directive line."""
    b = patch_to_sweep_bytes(patch)
    hex_vals = ", ".join(f"${v:02X}" for v in b)
    tags = []
    if patch.has_sweep:
        tags.append("sweep")
    if patch.has_vibrato:
        tags.append("vibrato")
    label = "+".join(tags) if tags else "no mod"
    return f"    .byte {hex_vals}  ; {patch.name} ({label})"


def patches_to_asm(
    patches: Sequence[SfxPatch],
    label: str = "sfx_data",
    include_index: bool = True,
) -> str:
    """Generate a complete assembly include file for a set of patches.

    Args:
        patches: Sequence of SfxPatch objects.
        label: Label for the data table.
        include_index: If True, emit SFX_* index constants.
    """
    lines = [
        "; SID SFX data — generated by sid_sfx authoring pipeline",
        f"; {len(patches)} entries, 7 bytes each",
        "; Format: voice, CR, freq_hi, freq_lo, AD, SR, pw_hi",
        ";",
    ]

    if include_index:
        for i, p in enumerate(patches):
            name_upper = p.name.upper().replace(" ", "_").replace("-", "_")
            lines.append(f"SFX_{name_upper} = {i}")
        lines.append("")

    lines.append(f"{label}:")
    for p in patches:
        lines.append(patch_to_asm_line(p))
    lines.append("")

    return "\n".join(lines)


def patches_to_asm_tables(
    patches: Sequence[SfxPatch],
    include_index: bool = True,
    include_curve_lut: bool = True,
    include_blaster_weights: bool = True,
) -> str:
    """Generate separate fixed-stride tables for the C64 engine.

    Emits:
        sfx_data[]: 7 bytes per entry, indexed by id*7
        sfx_sweep[]: 6 bytes per entry, indexed by id*6
        sfx_duration[]: 1 byte per entry (gate-on frames at 50Hz PAL)
        sfx_loop[]: 1 byte per entry (0=one-shot, 1=sustain)
        sfx_filter_mode[]: 1 byte per entry ($00=off, $10=LP, $20=BP, $40=HP)
        sfx_filter_cutoff[]: 1 byte per entry (FC_HI register)
        sfx_filter_resonance[]: 1 byte per entry (resonance nibble 0-15)
        sfx_filter_voice[]: 1 byte per entry (voice routing bit mask)
        exp_curve_lut[]: 16-byte exponential curve lookup (optional)
        blaster_weights[]: 8-byte weight-to-variant map (optional)
    """
    lines = [
        "; SID SFX tables — generated by sid_sfx authoring pipeline",
        f"; {len(patches)} entries",
        ";",
    ]

    if include_index:
        for i, p in enumerate(patches):
            name_upper = p.name.upper().replace(" ", "_").replace("-", "_")
            lines.append(f"SFX_{name_upper} = {i}")
        lines.append("")

    # sfx_data table: 7 bytes per entry
    lines.append("; 7 bytes per entry: voice, CR, freq_hi, freq_lo, AD, SR, pw_hi")
    lines.append("sfx_data:")
    for p in patches:
        lines.append(patch_to_asm_line(p))
    lines.append("")

    # sfx_sweep table: 6 bytes per entry
    lines.append("; 6 bytes per entry: target_hi, target_lo, frames, flags, vib_rate, vib_depth")
    lines.append("; flags: bit0=sweep, bit1=curve (0=linear, 1=exp), bit2=vibrato")
    lines.append("sfx_sweep:")
    for p in patches:
        lines.append(sweep_to_asm_line(p))
    lines.append("")

    # sfx_duration table: 1 byte per entry (gate-on frames at 50Hz PAL)
    lines.append("; 1 byte per entry: gate-on duration in frames (50Hz PAL)")
    lines.append("; For sustain SFX, duration is ignored — gate controlled by game events")
    lines.append("sfx_duration:")
    for p in patches:
        lines.append(f"    .byte {p.duration_frames}  ; {p.name}")
    lines.append("")

    # sfx_loop table: 1 byte per entry (0=one-shot, 1=sustain)
    lines.append("; 1 byte per entry: 0=one-shot (gate off after duration), 1=sustain (gate held by game)")
    lines.append("sfx_loop:")
    for p in patches:
        loop_val = 1 if p.loop else 0
        label = "sustain" if p.loop else "one-shot"
        lines.append(f"    .byte {loop_val}  ; {p.name} ({label})")
    lines.append("")

    # sfx_filter_mode: 1 byte per entry ($00=off, $10=lowpass, $20=bandpass, $40=highpass)
    filter_mode_map = {"off": 0x00, "lowpass": 0x10, "bandpass": 0x20, "highpass": 0x40}
    lines.append("; 1 byte per entry: SID filter mode ($00=off, $10=LP, $20=BP, $40=HP)")
    lines.append("sfx_filter_mode:")
    for p in patches:
        mode_byte = filter_mode_map.get(p.filter_mode, 0x00)
        lines.append(f"    .byte ${mode_byte:02X}  ; {p.name} ({p.filter_mode})")
    lines.append("")

    # sfx_filter_cutoff: 1 byte per entry (FC_HI value)
    lines.append("; 1 byte per entry: filter cutoff (FC_HI register)")
    lines.append("sfx_filter_cutoff:")
    for p in patches:
        cutoff = p.filter_cutoff if p.filter_mode != "off" else 0
        lines.append(f"    .byte ${cutoff:02X}  ; {p.name}")
    lines.append("")

    # sfx_filter_resonance: 1 byte per entry (resonance nibble 0-15)
    lines.append("; 1 byte per entry: filter resonance (0-15, shifted to top nibble at runtime)")
    lines.append("sfx_filter_resonance:")
    for p in patches:
        res = p.filter_resonance if p.filter_mode != "off" else 0
        lines.append(f"    .byte ${res:02X}  ; {p.name}")
    lines.append("")

    # sfx_filter_voice: 1 byte per entry (voice routing bit mask)
    lines.append("; 1 byte per entry: voice filter routing (bit0=v1, bit1=v2, bit2=v3)")
    lines.append("sfx_filter_voice:")
    for p in patches:
        voice_bit = (1 << (p.voice - 1)) if p.filter_mode != "off" else 0
        lines.append(f"    .byte ${voice_bit:02X}  ; {p.name} (voice {p.voice})")
    lines.append("")

    if include_curve_lut:
        hex_vals = ", ".join(f"${v:02X}" for v in EXP_CURVE_LUT)
        lines.append("; 16-byte exponential curve lookup")
        lines.append("exp_curve_lut:")
        lines.append(f"    .byte {hex_vals}")
        lines.append("")

    if include_blaster_weights:
        hex_vals = ", ".join(f"${v:02X}" for v in BLASTER_WEIGHTS)
        lines.append("; Blaster variant weight table (8 slots)")
        lines.append("; Maps random 0-7 to variant offset")
        lines.append("blaster_weights:")
        lines.append(f"    .byte {hex_vals}")
        lines.append("")

    return "\n".join(lines)


def save_asm(patches: Sequence[SfxPatch], path: str | Path, **kwargs):
    """Write patches to an assembly include file."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(patches_to_asm(patches, **kwargs))


def save_asm_tables(patches: Sequence[SfxPatch], path: str | Path, **kwargs):
    """Write patches as separate tables to an assembly include file."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(patches_to_asm_tables(patches, **kwargs))


def patch_to_game_blaster_bytes(patch: SfxPatch) -> bytes:
    """Convert a patch to the game's sfx_blaster_data format (7 bytes).

    Game format: filter_cutoff, CR, freq_hi, freq_lo, AD, SR, pw_hi
    (byte 0 is filter cutoff, NOT voice — differs from schema to_bytes())
    """
    # Always export filter_cutoff — the game engine applies its own bandpass
    # filter using this value, regardless of whether the patch has filter_mode on.
    cutoff = patch.filter_cutoff
    return bytes([
        cutoff,
        patch.cr_byte,
        patch.freq_hi,
        patch.freq_lo,
        patch.ad_byte,
        patch.sr_byte,
        patch.pw_hi,
    ])


def _vibrato_rate_index(rate_hz: float) -> int:
    """Map vibrato rate in Hz to engine rate table index.

    Engine rate table (frames per toggle at 50Hz PAL):
      idx 0: 12 frames (~2.1 Hz)
      idx 1:  6 frames (~4.2 Hz)
      idx 2:  5 frames (~5.0 Hz)
      idx 3:  3 frames (~8.3 Hz)
    """
    thresholds = [(3.0, 0), (4.5, 1), (6.5, 2)]
    for cutoff, idx in thresholds:
        if rate_hz < cutoff:
            return idx
    return 3


def _vibrato_depth_index(depth: int, frequency: int) -> int:
    """Map vibrato depth (SID freq units) to engine depth table index.

    Engine depth table (fraction of current frequency):
      idx 0: 1/8 freq  (12.5%)
      idx 1: 1/4 freq  (25%)
      idx 2: 3/8 freq  (37.5%)
      idx 3: 1/2 freq  (50%)
    """
    if frequency <= 0:
        return 0
    frac = depth / frequency
    if frac < 3 / 16:
        return 0
    if frac < 5 / 16:
        return 1
    if frac < 7 / 16:
        return 2
    return 3


def patch_to_game_sweep_bytes(patch: SfxPatch) -> bytes:
    """Convert a patch to the game's sfx_blaster_sweep format (4 bytes).

    Game format: target_hi, target_lo, frames, flags
    Flags byte:
      bit 0:    loop vibrato (1=reload frames on expiry, 0=one-shot)
      bits 1-3: unused
      bits 4-5: vibrato rate index (into rate_table [12,6,5,3] frames/toggle)
      bits 6-7: vibrato depth index (into depth_table [1/8, 1/4, 3/8, 1/2])
    Engine checks (flags AND #$F0) — if nonzero, vibrato runs.
    """
    flags = 0x00

    # Bit 0: loop vibrato for sustained drones
    is_loop = getattr(patch, "loop", False)
    if is_loop:
        flags |= 0x01

    # Pack vibrato into flags bits 4-7
    vibrato_rate = float(getattr(patch, "vibrato_rate", 0.0) or 0.0)
    vibrato_depth = int(getattr(patch, "vibrato_depth", 0) or 0)
    if vibrato_rate > 0 and vibrato_depth > 0:
        rate_idx = _vibrato_rate_index(vibrato_rate)
        depth_idx = _vibrato_depth_index(vibrato_depth, patch.frequency)
        flags |= (rate_idx & 0x03) << 4
        flags |= (depth_idx & 0x03) << 6

    frames = patch.sweep_frames if patch.sweep_frames > 0 else patch.duration_frames
    return bytes([
        patch.sweep_target_hi,
        patch.sweep_target_lo,
        frames & 0xFF,
        flags,
    ])


def patches_to_game_tables(
    patches: Sequence[SfxPatch],
    xwing_original: bytes | None = None,
    xwing_original_sweep: bytes | None = None,
) -> str:
    """Generate game-format sfx_blaster_data + sfx_blaster_sweep tables.

    This is the CANONICAL export for the c64 game engine. Output can be
    pasted directly into dankarmada.asm.

    Args:
        patches: Blaster variant patches (our replacements, indices 1+).
        xwing_original: 7-byte original xwing blaster data (index 0, preserved).
        xwing_original_sweep: 4-byte original xwing sweep data (index 0, preserved).
    """
    # Default original xwing if not provided
    if xwing_original is None:
        xwing_original = bytes([0x90, 0x21, 0x26, 0x18, 0x06, 0x08, 0x00])
    if xwing_original_sweep is None:
        xwing_original_sweep = bytes([0x04, 0xC3, 0x08, 0x03])

    all_data = [xwing_original]
    all_sweep = [xwing_original_sweep]
    names = ["xwing_blaster (original)"]

    for p in patches:
        all_data.append(patch_to_game_blaster_bytes(p))
        all_sweep.append(patch_to_game_sweep_bytes(p))
        names.append(p.name)

    lines = [
        "; === CANONICAL SFX BLASTER TABLES ===",
        "; Generated by c64audio pipeline — DO NOT HAND-EDIT",
        "; Generated by c64SIDkit",
        f"; {len(all_data)} entries",
        ";",
        "; Format: filter_cutoff, CR, freq_hi, freq_lo, AD, SR, pw_hi",
        "sfx_blaster_data:",
    ]
    for i, (data, name) in enumerate(zip(all_data, names)):
        hex_vals = ", ".join(f"${v:02X}" for v in data)
        lines.append(f"    .byte {hex_vals}  ; {i}: {name}")

    lines.append("")
    lines.append(f"; {len(all_sweep)} entries x 4 bytes: target_hi, target_lo, frames, flags")
    lines.append("sfx_blaster_sweep:")
    for i, (sweep, name) in enumerate(zip(all_sweep, names)):
        hex_vals = ", ".join(f"${v:02X}" for v in sweep)
        lines.append(f"    .byte {hex_vals}  ; {i}: {name}")

    lines.append("")
    lines.append("; weighted random: index by (star_rand AND #7) -> blaster ID")
    weights = list(range(len(all_data)))
    # Default weight distribution matching game convention
    if len(all_data) >= 7:
        weight_table = [0, 5, 6, 1, 1, 2, 3, 4]
    else:
        weight_table = [0] * 8
        for i in range(min(8, len(all_data))):
            weight_table[i] = i % len(all_data)
    hex_vals = ", ".join(str(w) for w in weight_table)
    lines.append(f"fire_weight_table:")
    lines.append(f"    .byte {hex_vals}")
    lines.append("")

    return "\n".join(lines)


def patches_to_c_array(patches: Sequence[SfxPatch], name: str = "sfx_data") -> str:
    """Generate a C-style byte array (for cc65 or testing)."""
    lines = [
        f"// SID SFX data — {len(patches)} entries, 7 bytes each",
        f"const unsigned char {name}[] = {{",
    ]
    for p in patches:
        b = p.to_bytes()
        hex_vals = ", ".join(f"0x{v:02X}" for v in b)
        lines.append(f"    {hex_vals},  /* {p.name} */")
    lines.append("};")
    return "\n".join(lines)
