"""Export SFX patches as assembly data tables.

Generates .asm include files matching the 7-byte-per-entry format
used by the C64 game engine (sound_auditor.asm / dankarmada.asm):

    voice(1B), CR(1B), freq_hi(1B), freq_lo(1B), AD(1B), SR(1B), pw_hi(1B)

Separate-table format adds:
    sfx_sweep[]: 6 bytes per entry (target_hi, target_lo, frames, flags, vib_rate, vib_depth)
    sweep_flags: bit 0 = sweep enable, bit 1 = curve (0=linear, 1=exponential), bit 2 = vibrato enable
"""

from __future__ import annotations

from pathlib import Path
from typing import Sequence

from sid_sfx.schema import SfxPatch


# 16-byte exponential curve lookup table (0-255 range, 16 steps).
# Approximates f(x) = 255 * (e^(x/15*3) - 1) / (e^3 - 1) for x in 0..15.
EXP_CURVE_LUT = bytes([
    0, 1, 2, 4, 7, 11, 17, 25,
    36, 51, 72, 101, 140, 178, 218, 255,
])

# Blaster weight table: maps random index (0-7) to blaster variant offset.
# 3/8 xwing, 2/8 heavy_repeater, 1/8 turbolaser, 1/8 tie_cannon, 1/8 ion_cannon
BLASTER_WEIGHTS = bytes([0, 0, 0, 1, 1, 2, 3, 4])


def patch_to_bytes(patch: SfxPatch) -> bytes:
    """Convert a patch to its 7-byte binary representation."""
    return patch.to_bytes()


def patch_to_sweep_bytes(patch: SfxPatch) -> bytes:
    """Convert a patch's sweep + vibrato parameters to 6-byte representation.

    Format: target_hi, target_lo, frames, flags, vib_rate, vib_depth
    flags: bit 0 = sweep enable, bit 1 = curve (0=linear, 1=exp), bit 2 = vibrato enable
    vib_rate: vibrato rate in quarter-Hz units (0-255 → 0-63.75 Hz)
    vib_depth: vibrato depth in SID freq units (high byte only, 0-255)
    """
    flags = 0x00
    target_hi = 0
    target_lo = 0
    frames = 0
    vib_rate = 0
    vib_depth = 0

    if patch.has_sweep:
        flags |= 0x01
        if patch.sweep_type == "exponential":
            flags |= 0x02
        target_hi = patch.sweep_target_hi
        target_lo = patch.sweep_target_lo
        frames = patch.sweep_frames if patch.sweep_frames > 0 else patch.duration_frames

    if patch.has_vibrato:
        flags |= 0x04
        # Encode rate as quarter-Hz (4x), clamp to byte
        vib_rate = min(255, round(patch.vibrato_rate * 4))
        # Encode depth high byte (>> 8), clamp to byte
        vib_depth = min(255, (patch.vibrato_depth >> 8) if patch.vibrato_depth > 255 else patch.vibrato_depth)

    return bytes([
        target_hi,
        target_lo,
        frames & 0xFF,
        flags,
        vib_rate,
        vib_depth,
    ])


def patch_to_asm_line(patch: SfxPatch) -> str:
    """Format a patch as a single .byte directive line."""
    b = patch.to_bytes()
    hex_vals = ", ".join(f"${v:02X}" for v in b)
    return f"    .byte {hex_vals}  ; {patch.name}"


def sweep_to_asm_line(patch: SfxPatch) -> str:
    """Format a patch's sweep/vibrato as a single .byte directive line."""
    b = patch_to_sweep_bytes(patch)
    hex_vals = ", ".join(f"${v:02X}" for v in b)
    tags = []
    if patch.has_sweep:
        tags.append("sweep")
    if patch.has_vibrato:
        tags.append("vibrato")
    label = "+".join(tags) if tags else "no mod"
    return f"    .byte {hex_vals}  ; {patch.name} ({label})"


def patches_to_asm(
    patches: Sequence[SfxPatch],
    label: str = "sfx_data",
    include_index: bool = True,
) -> str:
    """Generate a complete assembly include file for a set of patches.

    Args:
        patches: Sequence of SfxPatch objects.
        label: Label for the data table.
        include_index: If True, emit SFX_* index constants.
    """
    lines = [
        "; SID SFX data — generated by sid_sfx authoring pipeline",
        f"; {len(patches)} entries, 7 bytes each",
        "; Format: voice, CR, freq_hi, freq_lo, AD, SR, pw_hi",
        ";",
    ]

    if include_index:
        for i, p in enumerate(patches):
            name_upper = p.name.upper().replace(" ", "_").replace("-", "_")
            lines.append(f"SFX_{name_upper} = {i}")
        lines.append("")

    lines.append(f"{label}:")
    for p in patches:
        lines.append(patch_to_asm_line(p))
    lines.append("")

    return "\n".join(lines)


def patches_to_asm_tables(
    patches: Sequence[SfxPatch],
    include_index: bool = True,
    include_curve_lut: bool = True,
    include_blaster_weights: bool = True,
) -> str:
    """Generate separate fixed-stride tables for the C64 engine.

    Emits:
        sfx_data[]: 7 bytes per entry, indexed by id*7
        sfx_sweep[]: 6 bytes per entry, indexed by id*6
        exp_curve_lut[]: 16-byte exponential curve lookup (optional)
        blaster_weights[]: 8-byte weight-to-variant map (optional)
    """
    lines = [
        "; SID SFX tables — generated by sid_sfx authoring pipeline",
        f"; {len(patches)} entries",
        ";",
    ]

    if include_index:
        for i, p in enumerate(patches):
            name_upper = p.name.upper().replace(" ", "_").replace("-", "_")
            lines.append(f"SFX_{name_upper} = {i}")
        lines.append("")

    # sfx_data table: 7 bytes per entry
    lines.append("; 7 bytes per entry: voice, CR, freq_hi, freq_lo, AD, SR, pw_hi")
    lines.append("sfx_data:")
    for p in patches:
        lines.append(patch_to_asm_line(p))
    lines.append("")

    # sfx_sweep table: 6 bytes per entry
    lines.append("; 6 bytes per entry: target_hi, target_lo, frames, flags, vib_rate, vib_depth")
    lines.append("; flags: bit0=sweep, bit1=curve (0=linear, 1=exp), bit2=vibrato")
    lines.append("sfx_sweep:")
    for p in patches:
        lines.append(sweep_to_asm_line(p))
    lines.append("")

    if include_curve_lut:
        hex_vals = ", ".join(f"${v:02X}" for v in EXP_CURVE_LUT)
        lines.append("; 16-byte exponential curve lookup")
        lines.append("exp_curve_lut:")
        lines.append(f"    .byte {hex_vals}")
        lines.append("")

    if include_blaster_weights:
        hex_vals = ", ".join(f"${v:02X}" for v in BLASTER_WEIGHTS)
        lines.append("; Blaster variant weight table (8 slots)")
        lines.append("; Maps random 0-7 to variant offset")
        lines.append("blaster_weights:")
        lines.append(f"    .byte {hex_vals}")
        lines.append("")

    return "\n".join(lines)


def save_asm(patches: Sequence[SfxPatch], path: str | Path, **kwargs):
    """Write patches to an assembly include file."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(patches_to_asm(patches, **kwargs))


def save_asm_tables(patches: Sequence[SfxPatch], path: str | Path, **kwargs):
    """Write patches as separate tables to an assembly include file."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(patches_to_asm_tables(patches, **kwargs))


def patches_to_c_array(patches: Sequence[SfxPatch], name: str = "sfx_data") -> str:
    """Generate a C-style byte array (for cc65 or testing)."""
    lines = [
        f"// SID SFX data — {len(patches)} entries, 7 bytes each",
        f"const unsigned char {name}[] = {{",
    ]
    for p in patches:
        b = p.to_bytes()
        hex_vals = ", ".join(f"0x{v:02X}" for v in b)
        lines.append(f"    {hex_vals},  /* {p.name} */")
    lines.append("};")
    return "\n".join(lines)
