"""Export SFX patches as assembly data tables.

Generates .asm include files matching the 7-byte-per-entry format
used by the C64 game engine (sound_auditor.asm / dankarmada.asm):

    voice(1B), CR(1B), freq_hi(1B), freq_lo(1B), AD(1B), SR(1B), pw_hi(1B)
"""

from __future__ import annotations

from pathlib import Path
from typing import Sequence

from sid_sfx.schema import SfxPatch


def patch_to_bytes(patch: SfxPatch) -> bytes:
    """Convert a patch to its 7-byte binary representation."""
    return patch.to_bytes()


def patch_to_asm_line(patch: SfxPatch) -> str:
    """Format a patch as a single .byte directive line."""
    b = patch.to_bytes()
    hex_vals = ", ".join(f"${v:02X}" for v in b)
    return f"    .byte {hex_vals}  ; {patch.name}"


def patches_to_asm(
    patches: Sequence[SfxPatch],
    label: str = "sfx_data",
    include_index: bool = True,
) -> str:
    """Generate a complete assembly include file for a set of patches.

    Args:
        patches: Sequence of SfxPatch objects.
        label: Label for the data table.
        include_index: If True, emit SFX_* index constants.
    """
    lines = [
        "; SID SFX data — generated by sid_sfx authoring pipeline",
        f"; {len(patches)} entries, 7 bytes each",
        "; Format: voice, CR, freq_hi, freq_lo, AD, SR, pw_hi",
        ";",
    ]

    if include_index:
        for i, p in enumerate(patches):
            name_upper = p.name.upper().replace(" ", "_").replace("-", "_")
            lines.append(f"SFX_{name_upper} = {i}")
        lines.append("")

    lines.append(f"{label}:")
    for p in patches:
        lines.append(patch_to_asm_line(p))
    lines.append("")

    return "\n".join(lines)


def save_asm(patches: Sequence[SfxPatch], path: str | Path, **kwargs):
    """Write patches to an assembly include file."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(patches_to_asm(patches, **kwargs))


def patches_to_c_array(patches: Sequence[SfxPatch], name: str = "sfx_data") -> str:
    """Generate a C-style byte array (for cc65 or testing)."""
    lines = [
        f"// SID SFX data — {len(patches)} entries, 7 bytes each",
        f"const unsigned char {name}[] = {{",
    ]
    for p in patches:
        b = p.to_bytes()
        hex_vals = ", ".join(f"0x{v:02X}" for v in b)
        lines.append(f"    {hex_vals},  /* {p.name} */")
    lines.append("};")
    return "\n".join(lines)
