"""Built-in SFX presets matching the game's existing sound effects.

These mirror the 15 SFX definitions from the C64 game engine's sound_auditor.asm.
"""

from sid_sfx.schema import SfxPatch, Waveform


PRESETS = {
    "fire": SfxPatch(
        name="fire",
        voice=1, waveform=Waveform.SAWTOOTH,
        freq_hi=0x18, freq_lo=0x00,
        attack=0, decay=6, sustain=0, release=6,
        pw_hi=0x00, duration_frames=10,
        description="Sawtooth laser zap — sharp attack, quick decay",
    ),
    "explode": SfxPatch(
        name="explode",
        voice=2, waveform=Waveform.NOISE,
        freq_hi=0x08, freq_lo=0x00,
        attack=0, decay=9, sustain=0, release=9,
        pw_hi=0x00, duration_frames=15,
        description="Noise burst explosion — mid-frequency noise with slow decay",
    ),
    "hit": SfxPatch(
        name="hit",
        voice=1, waveform=Waveform.PULSE,
        freq_hi=0x0C, freq_lo=0x00,
        attack=0, decay=4, sustain=0, release=3,
        pw_hi=0x04, duration_frames=8,
        description="Short harsh pulse buzz — player damage",
    ),
    "weakpoint_hit": SfxPatch(
        name="weakpoint_hit",
        voice=1, waveform=Waveform.PULSE,
        freq_hi=0x09, freq_lo=0x00,
        attack=0, decay=7, sustain=2, release=7,
        pw_hi=0x05, duration_frames=12,
        description="Deeper metallic pulse — weakpoint damage with sustain",
    ),
    "enemy_hit": SfxPatch(
        name="enemy_hit",
        voice=1, waveform=Waveform.NOISE,
        freq_hi=0x10, freq_lo=0x00,
        attack=0, decay=2, sustain=0, release=0,
        pw_hi=0x00, duration_frames=6,
        description="Very short noise burst — enemy takes damage",
    ),
    "march": SfxPatch(
        name="march",
        voice=3, waveform=Waveform.TRIANGLE,
        freq_hi=0x06, freq_lo=0x00,
        attack=0, decay=4, sustain=0, release=4,
        pw_hi=0x00, duration_frames=10,
        description="Low triangle thud — marching bass",
    ),
    "kraft_alarm": SfxPatch(
        name="kraft_alarm",
        voice=3, waveform=Waveform.TRIANGLE,
        freq_hi=0x04, freq_lo=0x00,
        attack=0, decay=2, sustain=0, release=8,
        pw_hi=0x00, duration_frames=10,
        description="Rising triangle alarm tone",
    ),
    "game_over": SfxPatch(
        name="game_over",
        voice=1, waveform=Waveform.PULSE,
        freq_hi=0x18, freq_lo=0x00,
        attack=2, decay=2, sustain=10, release=8,
        pw_hi=0x08, duration_frames=45,
        description="Descending pulse tone with long sustain — game over",
    ),
    "death": SfxPatch(
        name="death",
        voice=2, waveform=Waveform.NOISE,
        freq_hi=0x14, freq_lo=0x00,
        attack=0, decay=10, sustain=0, release=12,
        pw_hi=0x00, duration_frames=20,
        description="Noise crash with long decay — player death",
    ),
    "warp": SfxPatch(
        name="warp",
        voice=3, waveform=Waveform.TRIANGLE,
        freq_hi=0x04, freq_lo=0x00,
        attack=2, decay=8, sustain=8, release=8,
        pw_hi=0x00, duration_frames=60,
        description="Slow rising triangle sweep — warp effect",
    ),
    "portal_ping": SfxPatch(
        name="portal_ping",
        voice=1, waveform=Waveform.TRIANGLE,
        freq_hi=0x20, freq_lo=0x00,
        attack=0, decay=2, sustain=0, release=0,
        pw_hi=0x00, duration_frames=5,
        description="Very brief high triangle blip — portal ping",
    ),
    "powerup": SfxPatch(
        name="powerup",
        voice=3, waveform=Waveform.TRIANGLE,
        freq_hi=0x1C, freq_lo=0xD6,
        attack=0, decay=8, sustain=10, release=0,
        pw_hi=0x00, duration_frames=15,
        description="Rising triangle arpeggio — powerup collect",
    ),
    "bounce": SfxPatch(
        name="bounce",
        voice=1, waveform=Waveform.SAWTOOTH,
        freq_hi=0x30, freq_lo=0x00,
        attack=0, decay=0, sustain=0, release=0,
        pw_hi=0x00, duration_frames=3,
        description="Ultra-short high sawtooth blip — bounce",
    ),
    "blaster_bolt": SfxPatch(
        name="blaster_bolt",
        voice=1, waveform=Waveform.SAWTOOTH,
        freq_hi=0x28, freq_lo=0x00,
        attack=0, decay=6, sustain=0, release=4,
        pw_hi=0x00, duration_frames=8,
        sweep_target_hi=0x03, sweep_target_lo=0x00,
        sweep_type="exponential",
        description="Descending sawtooth sweep — blaster bolt 'pew'",
    ),
    # --- Blaster variations (weighted random cycling in engine) ---
    # Weight 3/8: most common shot
    "xwing_blaster": SfxPatch(
        name="xwing_blaster",
        voice=1, waveform=Waveform.SAWTOOTH,
        freq_hi=0x80, freq_lo=0x00,
        attack=0, decay=4, sustain=0, release=3,
        pw_hi=0x00, duration_frames=6,
        sweep_target_hi=0x09, sweep_target_lo=0xFB,
        sweep_type="exponential",
        description="Quick bright blaster pew — X-wing style (weight 3/8)",
    ),
    # Weight 2/8: frequent mid-range punch
    "heavy_repeater": SfxPatch(
        name="heavy_repeater",
        voice=1, waveform=Waveform.SAWTOOTH,
        freq_hi=0x53, freq_lo=0x26,
        attack=0, decay=5, sustain=0, release=4,
        pw_hi=0x00, duration_frames=10,
        sweep_target_hi=0x04, sweep_target_lo=0xFD,
        sweep_type="exponential",
        description="Mid-range sawtooth sweep — heavy repeater (weight 2/8)",
    ),
    # Weight 1/8: occasional heavy hit
    "turbolaser": SfxPatch(
        name="turbolaser",
        voice=1, waveform=Waveform.SAWTOOTH,
        freq_hi=0x42, freq_lo=0x85,
        attack=0, decay=7, sustain=0, release=6,
        pw_hi=0x00, duration_frames=18,
        sweep_target_hi=0x02, sweep_target_lo=0xA9,
        sweep_type="exponential",
        description="Heavy sawtooth sweep — turbolaser blast (weight 1/8)",
    ),
    # Weight 1/8: occasional sharp crack
    "tie_cannon": SfxPatch(
        name="tie_cannon",
        voice=1, waveform=Waveform.PULSE,
        freq_hi=0x80, freq_lo=0x00,
        attack=0, decay=3, sustain=0, release=2,
        pw_hi=0x26, duration_frames=5,
        sweep_target_hi=0x1A, sweep_target_lo=0x9C,
        sweep_type="exponential",
        description="Thin high pulse sweep — TIE cannon crack (weight 1/8)",
    ),
    # --- Shield effects ---
    "shield_on_v3": SfxPatch(
        name="shield_on_v3",
        voice=3, waveform=Waveform.TRIANGLE,
        freq_hi=0x27, freq_lo=0xE9,
        attack=6, decay=8, sustain=10, release=8,
        pw_hi=0x00, duration_frames=60,
        vibrato_rate=15.0, vibrato_depth=100,
        description="600Hz triangle with 15Hz vibrato — Star Trek force field wobble",
    ),
    # Weight 1/8: rare deep boom
    "ion_cannon": SfxPatch(
        name="ion_cannon",
        voice=1, waveform=Waveform.PULSE,
        freq_hi=0x31, freq_lo=0xE4,
        attack=0, decay=8, sustain=0, release=7,
        pw_hi=0x14, duration_frames=20,
        sweep_target_hi=0x01, sweep_target_lo=0xFF,
        sweep_type="exponential",
        description="Deep narrow-pulse sweep — ion cannon boom (weight 1/8)",
    ),
}
